#
# Copyright 2026 Benjamin Kiessling
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.
"""
Generator/parser for the Unicode character data tables in
`kraken.lib.bidi._data`.

To regenerate the tables for a new Unicode version, download the following
files from https://www.unicode.org/Public/<version>/ucd/ into a directory:

    DerivedBidiClass.txt
    BidiBrackets.txt
    BidiMirroring.txt

and run:

    python -m kraken.lib.bidi._make_tables <ucd_dir> <version>
"""
import re
import sys
from pathlib import Path


def _parse_ucd(path: Path) -> list[tuple[int, int, list[str]]]:
    records = []
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(';')]
        m = re.match(r'^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))$|^([0-9A-F]{4,6})$', fields[0])
        if not m:
            continue
        if m.group(3):
            first = last = int(m.group(3), 16)
        else:
            first, last = int(m.group(1), 16), int(m.group(2), 16)
        records.append((first, last, fields[1:]))
    return records


_MISSING_RE = re.compile(r'^#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+);\s*([A-Za-z_]+)', re.M)
_LONG_NAMES = {'Left_To_Right': 'L',
               'Right_To_Left': 'R',
               'Arabic_Letter': 'AL',
               'European_Terminator': 'ET'}


def make_class_ranges(path: Path) -> list[tuple[int, int, str]]:
    explicit = sorted((first, last, fields[0]) for first, last, fields in _parse_ucd(path))
    entries = [e for e in explicit if e[2] != 'L']
    for m in _MISSING_RE.finditer(path.read_text(encoding='utf-8')):
        first, last = int(m.group(1), 16), int(m.group(2), 16)
        cls = _LONG_NAMES[m.group(3)]
        if cls == 'L':
            continue
        pos = first
        for efirst, elast, _ in explicit:
            if elast < first:
                continue
            if efirst > last:
                break
            if efirst > pos:
                entries.append((pos, efirst - 1, cls))
            pos = max(pos, elast + 1)
            if pos > last:
                break
        if pos <= last:
            entries.append((pos, last, cls))
    entries.sort()
    merged = []
    for first, last, cls in entries:
        if merged and merged[-1][2] == cls and merged[-1][1] + 1 == first:
            merged[-1][1] = last
        else:
            merged.append([first, last, cls])
    return [tuple(e) for e in merged]


def make_brackets(path: Path) -> list[tuple[int, int, str]]:
    brackets = []
    for first, last, fields in _parse_ucd(path):
        if fields[1] in ('o', 'c'):
            assert first == last
            brackets.append((first, int(fields[0], 16), fields[1]))
    return sorted(brackets)


def make_mirrors(path: Path) -> list[tuple[int, int]]:
    mirrors = []
    for first, last, fields in _parse_ucd(path):
        assert first == last
        mirrors.append((first, int(fields[0], 16)))
    return sorted(mirrors)


def main():
    ucd_dir = Path(sys.argv[1])
    version = sys.argv[2]

    classes = make_class_ranges(ucd_dir / 'DerivedBidiClass.txt')
    brackets = make_brackets(ucd_dir / 'BidiBrackets.txt')
    mirrors = make_mirrors(ucd_dir / 'BidiMirroring.txt')

    out = Path(__file__).parent / '_data.py'
    with open(out, 'w', encoding='utf-8') as fp:
        fp.write('# autogenerated. do not edit.\n'
                 '#\n'
                 f'# Source: Unicode Character Database {version}\n'
                 '#   DerivedBidiClass.txt, BidiBrackets.txt, BidiMirroring.txt\n'
                 '# (c) Unicode, Inc., distributed under the Unicode License v3\n'
                 '# (https://www.unicode.org/license.txt).\n'
                 '"""\n'
                 'Unicode character data tables for kraken.lib.bidi.\n'
                 '"""\n\n')
        fp.write(f"UCD_VERSION = '{version}'\n\n")
        fp.write('# (first, last, Bidi_Class) for all code points with a class other\n'
                 '# than L, sorted and merged; anything not covered is L\n')
        fp.write('BIDI_CLASS_RANGES = (\n')
        for first, last, cls in classes:
            fp.write(f"    (0x{first:04X}, 0x{last:04X}, '{cls}'),\n")
        fp.write(')\n\n')
        fp.write('# code point -> (Bidi_Paired_Bracket, Bidi_Paired_Bracket_Type)\n')
        fp.write('BRACKETS = {\n')
        for cp, paired, typ in brackets:
            fp.write(f"    0x{cp:04X}: (0x{paired:04X}, '{typ}'),\n")
        fp.write('}\n\n')
        fp.write('# code point -> Bidi_Mirroring_Glyph\n')
        fp.write('MIRRORED = {\n')
        for cp, mirror in mirrors:
            fp.write(f'    0x{cp:04X}: 0x{mirror:04X},\n')
        fp.write('}\n')
    print(f'wrote {out}: {len(classes)} class ranges, {len(brackets)} brackets, '
          f'{len(mirrors)} mirrors')


if __name__ == '__main__':
    main()
