package:
  name: kraken
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

requirements:
  build:
     - python
     - setuptools
     - pbr
  run:
     - python
     - python-bidi
     - lxml
     - regex
     - requests
     - click>=7.0
     - numpy
     - pillow>=6.2.2
     - scipy
     - protobuf>=3.0
     - jinja2
     - conda-forge::torchvision
     - conda-forge::pytorch>=1.5.0,<1.11
     - cudatoolkit>=9.2
     - jsonschema
     - scikit-image>=0.17.0,<=0.19.1
     - shapely
     - pyvips
     - imagemagick>=7.1.0
     - coremltools>=3.3
     - libffi # [osx]
about:
  home: http://kraken.re
  license: Apache License
  summary: 'OCR/HTR engine for all the languages'
